" Auto add head info
" .py file into add header

function HeaderPython()
		call setline(1, "#!/usr/bin/env/ python")
		call append(1, "# -*- coding: utf-8 -*-")
		call append(2, "# Author: noneface")
		normal G
		normal o
endf

autocmd bufnewfile *.py call HeaderPython()

" normal settings

set nocompatible
filetype off

set number
set showtabline=0

syntax on

set background=dark

set nowrap
set tabstop=4
set expandtab
set showmatch
set laststatus=2
set fenc=utf-8
set hlsearch
set cursorline
set t_Co=256
"""""""""""""""""""



" Vundel plugin management

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'fholgado/minibufexpl.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Yggdroot/indentLine'
Plugin 'tell-k/vim-autopep8'
Plugin 'majutsushi/tagbar'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'kien/ctrlp.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'flazz/vim-colorschemes'
Plugin 'tpope/vim-fugitive'
Plugin 'davidhalter/jedi-vim'

call vundle#end()
filetype plugin indent on

"""

""  Plugins settings

"" for indetLine
let g:indentLine_char = '¦'
let g:indentLine_enabled = 1
let g:indentLine_color_term = 239
let g:autopep8_disable_show_diff=1

"" for NERDTree
nnoremap gt :NERDTreeToggle<CR>
let NERDChristmasTree=1
let NERDTreeHighlightCursorline=1
let NERDTreeWinPos='left'
let NERDTreeIgnore=['^\.', '\~$', '\.pyc$', '\.swp$', '\.git$']


"" for tagbar
map gb :TagbarToggle<CR>


"" for airline

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enable = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_seq = '|'
let g:airline_theme="solarized"
let g:airline_solarized_bg="dark"


"" for theme
colorscheme solarized
